### PR TITLE
add report

### PR DESCRIPTION
**Pull request by noraj**
replace & close #5

### CODE REVIEW

**Comment by wetw0rk** [comment]
Do you have a netsecfocus account? May be easier to message me on there and we can work together on putting ur tool in the repo (and others in the future).

Edit: https://mm.netsecfocus.com/join/

**Comment by noraj** [comment]
I like Mattermost a lot but I'm not willing to create an account on a third party website that I will use only one time for one contribution on one repository. Things could have been different if oAuth was enabled let's say with Github.

On the other hand you can enable the Github "discussion" feature that is exactly meant for that:
image

**Comment by wetw0rk** [comment]
Trust me that Netsec is safer than your local Starbucks, but I understand. Ill try to get that feature setup tomorrow if I have a chance.

Id reconsider Netsec though great community, love em ❤

**Comment by wetw0rk** [comment]
Please add this to the newly created structure along with a README

**Comment by noraj** [comment]
@wetw0rk I'm not sure of what new structure you are talking about?

**Comment by wetw0rk** [comment]
@noraj Sorry for the late response started OSEP so been a bit hectic. Submit your tools and a README here:

https://github.com/wetw0rk/AWAE-PREP/tree/master/Community%20Contributions%20%26%20Enhancements

So for example it should look like this:

```
root@kali:~/AWAE-PREP/Community Contributions & Enhancements# ls -l
total 12
drwxr-xr-x 3 root root 4096 Feb 24 09:05  Challenges
drwxr-xr-x 3 root root 4096 Feb 24 09:05 'Code Improvements'
-rw-r--r-- 1 root root    0 Feb 24 09:05  README.md
drwxr-xr-x 2 root root 4096 Feb 24 09:05  Tutorials
root@kali:~/AWAE-PREP/Community Contributions & Enhancements# mkdir Tools
root@kali:~/AWAE-PREP/Community Contributions & Enhancements# cd Tools/
root@kali:~/AWAE-PREP/Community Contributions & Enhancements/Tools# mkdir YOUR_TOOL_NAME
root@kali:~/AWAE-PREP/Community Contributions & Enhancements/Tools# cd YOUR_TOOL_NAME/
root@kali:~/AWAE-PREP/Community Contributions & Enhancements/Tools/YOUR_TOOL_NAME# touch README.md 
```

You'd be the first person to submit a tool ;)

**Pull request closed without merging**
